### ISSUE TITLE
Verlinkung "Textbaustein hinzufügen" in der Verwaltung der Textbaustein Kategorien

### ISSUE THREAD

**Issue by OlliW** [FreiconOSS/otobo-textmodule#16]
![image](https://github.com/FreiconOSS/otobo-textmodule/assets/80096822/f4c99f6f-7e2b-41c1-9cc6-1c53f2d13ca4)

**Comment by Lucsaan** [comment]
Button wird jetzt direkt in den Textbaustein Kategorien angezeigt und führt zu Editormaske zur Eingabe eines neuen Textmoduls
![image](https://github.com/FreiconOSS/otobo-textmodule/assets/11646726/e32cb68b-5140-4404-886d-00117036b701)
