### ISSUE TITLE
Doku für OPM erstellen

### ISSUE THREAD

**Issue by OlliW** [FreiconOSS/otobo-textmodule#7]
Bitte fügt mindestens unter doc/en eine Doku als PDF ein.

**Comment by Lucsaan** [comment]
Dokumentation wird jetzt über die jeweilige README (Deutsch/Englisch) in ein Pdf der jeweiligen Sprache generiert und in doc/en oder doc/de abgespeichert und kann nach Installation des Pakets im Paketmanager heruntergeladen werden. 

Vielen dank an @Paprikant
